# Generated by Django 3.0.8 on 2020-08-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='form_message',
        ),
    ]
