# Generated by Django 3.0.8 on 2020-08-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0002_remove_appointment_form_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_message',
            field=models.CharField(default='I want to book an appointment', max_length=250),
        ),
    ]
