# Generated by Django 3.0.8 on 2020-08-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0003_appointment_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
