# Generated by Django 3.0.8 on 2020-08-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0004_auto_20200822_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
